FROM centos:7

RUN yum install -y -q https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y -q \
  && yum install -y -q https://rhel7.iuscommunity.org/ius-release.rpm
RUN yum install -y -q jq git2u
